[package]
name = "qzgen"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.26"
clap = { version = "4.3.8", features = ["derive"] }
markdown = "0.3.0"
once_cell = "1.18.0"
rand = "0.8.5"
regex = "1.8.4"
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.97"
termion = "2.0.1"
