[package]
name = "qzgen"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.26"
clap = { version = "4.0.29", features = ["derive"] }
glob = "0.3.1"
markdown_to_text = "1.0.0"
rand = "0.8.5"
regex = "1.8.4"
reqwest = { version = "0.11.18", features = ["blocking"] }
